# Site settings
title: PR-Patterns
description: A collaborative database of real-world code review patterns and anti-patterns
baseurl: "/PR-Patterns"  # The repository name, keep this as is for GitHub Pages
url: ""

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Navigation
aux_links:
  "PR-Patterns on GitHub":
    - "//github.com/NeuralBloom/PR-Patterns"

# Search settings
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2024 PR-Patterns Contributors. Distributed under an MIT license."

# Collections
collections:
  patterns:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: patterns
    values:
      layout: pattern
      nav_order: 1
      has_children: false

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE

# Plugin settings
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy code button
enable_copy_code_button: true

# Custom SASS/CSS
sass:
  style: compressed

# Custom callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow
